### ISSUE TITLE
Parser getting last token only?

### ISSUE THREAD

**Issue by Infiniti20** [davidcallanan/py-myopl-code#10]
When I do something like this:
`1+2`
it returns:
`INT:2`
Not anything else.
IDK what's causing it.
Also, what does `tok.type` do? It gives me a syntax error, and the syntax seems weird.

**Comment by ibnsultan** [comment]
My guess is that you're still on episode 1 of this tutorial, just do some comparison between your code and the one in the repo, there is no problem with the source code, even if there is, it would be very hard to find it with just expression such as that.

and one more thing you need to have an idea about python, course it will make no sense if you just copy and paste

Thanks, happy coding

**Comment by Infiniti20** [comment]
No, I'm not on EP. 1. I realized what happened. And I have over 5 years of experience with Python. This guy codes in a different type of style then me.

**Comment by Infiniti20** [comment]
> My guess is that you're still on episode 1 of this tutorial, just do some comparison between your code and the one in the repo, there is no problem with the source code, even if there is, it would be very hard to find it with just expression such as that.
> 
> and one more thing you need to have an idea about python, course it will make no sense if you just copy and paste
> 
> Thanks, happy coding

No, I'm not on EP. 1. I realized what happened. And I have over 5 years of experience with Python. This guy codes in a different type of style then me.
