### ISSUE TITLE
Issue With Interpreter

### ISSUE THREAD

**Issue by henryboisdequin** [davidcallanan/py-myopl-code#4]
Firstly, thank you for making this wonderful series, I hope to make my own language one day and this is a great starting point. I have had an issue with my interpreter in video three in the series. When I type a digit or an operation, it states invalid syntax (attached to this issue). My code linked to this issue as well. Before this issue, everything was going well but now my language doesn't function properly. Any help would be appreciated.
![Screen Shot 2020-06-30 at 10 02 56 AM](https://user-images.githubusercontent.com/65845077/86083865-ff685d80-bab8-11ea-8d1a-be15da6ae415.png)
![Screen Shot 2020-06-30 at 10 02 10 AM](https://user-images.githubusercontent.com/65845077/86083882-098a5c00-bab9-11ea-9ffd-08c489561f65.png)
![Screen Shot 2020-06-30 at 10 02 23 AM](https://user-images.githubusercontent.com/65845077/86083891-11e29700-bab9-11ea-8e94-706161547335.png)
![Screen Shot 2020-06-30 at 10 02 28 AM](https://user-images.githubusercontent.com/65845077/86083902-1909a500-bab9-11ea-9504-fef8122392dd.png)

**Comment by davidcallanan** [comment]
@henryboisdequin This is a syntax error caused by the parser. You should take a look at your parser code.

**Comment by henryboisdequin** [comment]
Thanks, I'll have a look.
