### ISSUE TITLE
Getting InvalidSyntaxError

### ISSUE THREAD

**Issue by Seb-CD** [davidcallanan/py-myopl-code#44]
var animal = random(1, 3)

if animal = 1 then
    print("You have Pikachu!")
elif animal = 2 then
    print("You have Charmander!")
else then
    print("You have Squirtle!")
end

I made the keywords lowercase and added a random function, but it says the if is causing an InvalidSyntaxError, the example works, and I don't know what I did differently, it says a token can't appear after another token.

**Comment by foxypiratecove37350** [comment]
- At which episode are you?
- Did you recopied manually the code or cloned this repo?
- What are your modifications?
- Can you share the code of what you modified?

**Comment by Seb-CD** [comment]
ahh this is a year old and I don't have my old files because my old computer is pretty much broken, so I'm just going to close this since I can't recreate the issue and it's not really relevant anymore.
